version: '3.8'

services:
  scorelab-api:
    container_name: scorelab-api
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: npm run dev

  mongodb:
    image: mongo
    container_name: scorelab-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: